# Generated by Django 5.2.3 on 2026-02-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_fix_featured_image_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='When this post should stop being featured', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
