# Generated by Django 5.2.1 on 2026-02-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_alter_category_options_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
