# Generated by Django 5.2.3 on 2026-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='Automatically expires 24 hours after being featured', null=True),
        ),
    ]
